# apiVersion: v1
# kind: Service
# metadata:
#   name: platformnpservice-srv
# spec:
#   type: NodePort
#   selector:
#     app: platformservice
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#       nodePort: 30010

apiVersion: v1
kind: Service
metadata:
  name: platformnpservice-srv
spec:
  type: NodePort
  selector:
    app: platformservice
  ports:
  - port: 80                # Port mà Service "nghe" bên trong cluster
    targetPort: 8080        # Port của container ứng dụng (Pod)
    nodePort: 30010
    