
name: AI PR Reviews

on:
  pull_request:
    types: [opened, synchronize]
permissions:
  pull-requests: write
  contents: read
jobs:
  gpt_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install openai requests

      - name: Read ./scripts/prompt_input.txt into global env var
        id: read_prompt
        run: |
          # chmod 775 -R ./scripts && ./scripts/prompt_input.txt
          PROMPT_TEXT="$(cat ./scripts/prompt_input.txt)"
          echo "PROMPT_TEXT<<EOF" >> $GITHUB_ENV
          echo "$PROMPT_TEXT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Debug - show prompt
        run: echo "$PROMPT_TEXT"

      - name: Get PR diff
        id: diff
        run: |
          echo "DIFF<<EOF" >> $GITHUB_ENV
         
          git fetch origin main
          git diff origin/main..HEAD -- '*.js' '*.jsx' '*.ts' '*.tsx' > diff.txt
          cat diff.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Run GPT Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          
        run: |
            pip install openai requests --upgrade
        
            python3 - <<EOF
            import openai
            import os
            import requests
        
            client = openai.OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
        
            with open("diff.txt", "r") as f:
                diff = f.read()
            with open("./scripts/prompt_input.txt", "r") as file:
                prompt_text = file.read().strip() 
            title = os.getenv("PR_TITLE")
            prompt = f"You are a code review AI. Please review the following pull request using this checklist: {prompt_text}\n\n with pr title {title}  \n\n{diff[:3500]} Suggestions to fix"
            print(promt)
            # response = client.chat.completions.create(
            #     model="gpt-4",
            #     messages=[
            #         {"role": "user", "content": prompt}
            #     ],
            #     max_tokens=500
            # )
        
            # review_comment = response.choices[0].message.content
        
            # # Post to PR
            # repo = os.getenv("GITHUB_REPOSITORY")
            # pr_number = os.getenv("PR_NUMBER")
            # url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
            # headers = {
            #     "Authorization": f"Bearer {os.getenv('GITHUB_TOKEN')}",
            #     "Accept": "application/vnd.github+json"
            # }
            # data = {
            #     "body": f"🤖 **AI Code Review Suggestions:**\n\n{review_comment}"
            # }
        
            # r = requests.post(url, headers=headers, json=data)
            # if r.status_code != 201:
            #     raise Exception(f"Failed to post comment: {r.text}")
            # EOF
        